### ISSUE TITLE
0.11.0 - Production - Processors is ran against cached return values

### ISSUE THREAD

**Issue by Blystad** [dandelion/dandelion-datatables#273]
Hey,

So, my dandelion javascript files are starting to look a bit odd...It seems processors are ran against cached values causing for instance "aLengthMenu" to look like this after a while: `[[[[[[[[[[[[[[[[[[[100,250,500],[100,250,500]]]]]]]]]]]]]]]]]`. This is not a problem in development.

**Comment by tduchateau** [comment]
I can't reproduce :-(

Please post your configuration options. (?ddl-debug&ddl-debug-page=options)
How did you enabled the production profile?

**Comment by Blystad** [comment]
Using `-Ddandelion.profile.active=production`.

With that set, ddl-debug will be disabled :) But I'll override that and get back to you tomorrow.

**Comment by tduchateau** [comment]
Thanks!

> With that set, ddl-debug will be disabled

Note that with `-Ddandelion.profile.active=production` you'll need a `dandelion/dandelion_production.properties` file containing:

````
tool.debugger=true
````
So that the debugger will be available.

**Comment by Blystad** [comment]
So, I tried using the debugger site but that didn't work:

```
2015-02-03 10:17:08.259  WARN 18349 --- [tp1557712937-50] org.eclipse.jetty.server.HttpChannel     : /fileservice/manage?ddl-debug

com.github.dandelion.core.DandelionException: An error occured when generating the "null"debug page.
	at com.github.dandelion.core.web.handler.impl.DebuggerPostHandler.handle(DebuggerPostHandler.java:105)
	at com.github.dandelion.core.web.handler.AbstractHandlerChain.doHandle(AbstractHandlerChain.java:68)
	at com.github.dandelion.core.web.handler.AbstractHandlerChain.doHandle(AbstractHandlerChain.java:73)
	at com.github.dandelion.core.web.handler.AbstractHandlerChain.doHandle(AbstractHandlerChain.java:73)
	at com.github.dandelion.core.web.handler.AbstractHandlerChain.doHandle(AbstractHandlerChain.java:73)
	at com.github.dandelion.core.web.handler.AbstractHandlerChain.doHandle(AbstractHandlerChain.java:73)
	at com.github.dandelion.core.web.DandelionFilter.doFilter(DandelionFilter.java:139)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:595)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.__doHandle(ContextHandler.java:1125)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:191)
	at org.eclipse.jetty.server.Dispatcher.error(Dispatcher.java:77)
	at org.eclipse.jetty.server.handler.ErrorHandler.handle(ErrorHandler.java:91)
	at org.eclipse.jetty.server.Response.sendError(Response.java:597)
	at org.eclipse.jetty.server.Response.sendError(Response.java:544)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:647)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.__doHandle(ContextHandler.java:1125)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:620)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:540)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException: null
	at com.github.dandelion.core.cache.CacheManager.generateRequestCacheKey(CacheManager.java:65)
	at com.github.dandelion.core.asset.AssetQuery.perform(AssetQuery.java:120)
	at com.github.dandelion.core.web.handler.debug.AssetsDebugPage.getCustomParameters(AssetsDebugPage.java:132)
	at com.github.dandelion.core.web.handler.debug.AbstractDebugPage.getParameters(AbstractDebugPage.java:95)
	at com.github.dandelion.core.web.handler.impl.DebuggerPostHandler.getPage(DebuggerPostHandler.java:138)
	at com.github.dandelion.core.web.handler.impl.DebuggerPostHandler.getView(DebuggerPostHandler.java:127)
	at com.github.dandelion.core.web.handler.impl.DebuggerPostHandler.handle(DebuggerPostHandler.java:101)
	... 40 common frames omitted
```

In any case, I've set these settings in my `resources/dandelion/datatables/datatables.properties` file:

```
global.feature.displayLength=250
global.feature.lengthMenu=100,250,500,1000;100,250,500,1000
```

I then load in one website with a datatable (`/devices`), which works fine. Then I load the next one (`/filemanager`) and this is the resulting javascript:

```
var oTable_fileservice;var oTable_fileservice_params={"columns":[{"defaultContent":""},{"defaultContent":""},{"defaultContent":""},{"defaultContent":""},{"defaultContent":""}],"length":100,"processing":true,"aLengthMenu":[[[100,250,500,1000],[100,250,500,1000]]]};$(document).ready(function(){oTable_fileservice=$('#fileservice').DataTable(oTable_fileservice_params);});
```

I then load a third page, `/wifi` and this is the resulting JavaScript:

```
var oTable_wifitable;var oTable_wifitable_params={"columns":[{"defaultContent":""},{"defaultContent":""},{"defaultContent":""}],"length":100,"processing":true,"aLengthMenu":[[[[[[[[100,250,500,1000],[100,250,500,1000]]]]]]]]};$(document).ready(function(){oTable_wifitable=$('#wifitable').DataTable(oTable_wifitable_params);});
```

**Comment by tduchateau** [comment]
The NPE is already fixed in the next snapshot (not published yet).
I'm still investigating about the mess with the aLengthMenu parameter, not sure if it's a DDL or a DDL-DT issue. I'll keep you posted.

Thanks!

**Comment by tduchateau** [comment]
Please give a try with the latest snapshots.
