### ISSUE TITLE
DandelionFilter and Jetty idle timeout

### ISSUE THREAD

**Issue by harbulot** [dandelion/dandelion-datatables#280]
This is a problem that I've noticed when upgrading from Dandelion Datatables 0.8.14 to 0.10.1 and also the latest 0.11.0-SNAPSHOT, using Thymeleaf.

This problem can be tested with the demo project available here: https://github.com/harbulot/dandelion-datatables-issue-279

Essentially, in some cases, the main page can take a long time to be sent back to the browser, from the time the request is made. This is not really related to loading additional resources. Rather, it's about the request being stalled for a while before any response is sent back, even on a localhost connection.

I'm not entirely sure what caused this, but I've managed to track it down to the [idle timeout set in the Jetty connector](http://stackoverflow.com/questions/25548341/jetty-idletimeout) (which I've used in the example above): it is generally 30 seconds, by default (this can be set programmatically with `connector.setIdleTimeout(30000)`). This is more or less exactly the stalled delay experienced (and this varies accordingly when changing this parameter).

I can't reproduce this for all requests, but this seems to happen more often for requests with empty responses (e.g. directions, such as `/` -> `/page1` in the example project above).

We can see exceptions such as this in the logs:

```
21:04:48.823 [qtp191382150-33 - /] DEBUG o.s.web.servlet.DispatcherServlet - Rendering view [org.springframework.web.servlet.view.RedirectView: unnamed; URL [/page1]] in DispatcherServlet with name 'org.springframework.web.servlet.DispatcherServlet-542060780'
21:04:48.823 [qtp191382150-33 - /] DEBUG o.s.b.f.s.DefaultListableBeanFactory - Returning cached instance of singleton bean 'requestDataValueProcessor'
21:04:48.823 [qtp191382150-33 - /] DEBUG o.s.s.w.c.HttpSessionSecurityContextRepository - SecurityContext is empty or contents are anonymous - context will not be stored in HttpSession.
21:04:48.824 [qtp191382150-33 - /] DEBUG o.e.jetty.server.HttpConnection - org.eclipse.jetty.server.HttpConnection$CommitCallback@4327b8b5 generate: NEED_HEADER (null,[p=0,l=0,c=0,r=0],true)@START
21:04:48.824 [qtp191382150-33 - /] DEBUG o.e.jetty.server.HttpConnection - org.eclipse.jetty.server.HttpConnection$CommitCallback@4327b8b5 generate: FLUSH ([p=0,l=319,c=8192,r=319],[p=0,l=0,c=0,r=0],true)@COMPLETING
21:04:48.824 [qtp191382150-33 - /] DEBUG org.eclipse.jetty.io.WriteFlusher - write: WriteFlusher@4ef932de{IDLE} [HeapByteBuffer@3e341704[p=0,l=319,c=8192,r=319]={<<<HTTP/1.1 302 Foun....v20130815)||||>>>://localhost:9012...???????????????}]
21:04:48.824 [qtp191382150-33 - /] DEBUG org.eclipse.jetty.io.WriteFlusher - update WriteFlusher@4ef932de{WRITING}:IDLE-->WRITING
21:04:48.825 [qtp191382150-33 - /] DEBUG org.eclipse.jetty.io.ChannelEndPoint - flushed 319 SelectChannelEndPoint@fc438e5{/0:0:0:0:0:0:0:1:60695<r-l>/0:0:0:0:0:0:0:1:9012,o=true,is=false,os=false,fi=FillInterest@bfbbdc5{false,null},wf=WriteFlusher@4ef932de{WRITING},it=30000}{HttpConnection@51d0f3ca{FILLING},g=HttpGenerator{s=COMPLETING},p=HttpParser{s=END,0 of 0}}{io=0,kio=0,kro=1}
21:04:48.825 [qtp191382150-33 - /] DEBUG org.eclipse.jetty.io.WriteFlusher - flushed true
21:04:48.825 [qtp191382150-33 - /] DEBUG org.eclipse.jetty.io.WriteFlusher - update WriteFlusher@4ef932de{IDLE}:WRITING-->IDLE
21:04:48.825 [qtp191382150-33 - /] DEBUG o.e.jetty.server.HttpConnection - org.eclipse.jetty.server.HttpConnection$CommitCallback@4327b8b5 generate: DONE ([p=319,l=319,c=8192,r=0],[p=0,l=0,c=0,r=0],true)@END
21:04:48.825 [qtp191382150-33 - /] DEBUG o.s.web.servlet.DispatcherServlet - Successfully completed request
21:04:48.825 [qtp191382150-33 - /] DEBUG o.s.s.w.a.ExceptionTranslationFilter - Chain processed normally
21:04:48.825 [qtp191382150-33 - /] DEBUG o.s.s.w.c.SecurityContextPersistenceFilter - SecurityContextHolder now cleared, as request processing completed
21:04:48.826 [qtp191382150-33 - /] DEBUG org.eclipse.jetty.server.HttpChannel - 
org.eclipse.jetty.io.EofException: Closed
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:171) ~[jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at java.io.OutputStream.write(OutputStream.java:75) ~[na:1.8.0_45]
	at com.github.dandelion.core.web.DandelionFilter.doFilter(DandelionFilter.java:149) ~[classes/:na]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1477) ~[jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:503) ~[jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:211) ~[jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1096) ~[jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:432) ~[jetty-servlet-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175) ~[jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1030) ~[jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136) ~[jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:201) ~[jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) ~[jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.Server.handle(Server.java:445) ~[jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:268) ~[jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:229) [jetty-server-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358) [jetty-io-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601) [jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532) [jetty-util-9.0.5.v20130815.jar:9.0.5.v20130815]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
21:04:48.826 [qtp191382150-33] DEBUG org.eclipse.jetty.http.HttpParser - close HttpParser{s=END,0 of 0}
21:04:48.826 [qtp191382150-33] DEBUG org.eclipse.jetty.http.HttpParser - END --> CLOSED
21:04:48.826 [qtp191382150-33] DEBUG o.e.jetty.io.AbstractConnection - fillInterested HttpConnection@51d0f3ca{FILLING},g=HttpGenerator{s=END},p=HttpParser{s=CLOSED,0 of -1}
21:04:48.826 [qtp191382150-33] DEBUG org.eclipse.jetty.server.HttpChannel - HttpChannelOverHttp@3cff2ef9{r=1,a=IDLE,uri=-} handle exit, result COMPLETE
```

There are also a number of timeout exceptions like this one:

```
21:05:08.984 [Scheduler-1874154700] DEBUG org.eclipse.jetty.io.IdleTimeout - SelectChannelEndPoint@416fbabb{/0:0:0:0:0:0:0:1:60680<r-l>/0:0:0:0:0:0:0:1:9012,o=true,is=false,os=true,fi=FillInterest@4550264e{false,null},wf=WriteFlusher@52b080{IDLE},it=30000}{HttpConnection@d9edc09{INTERESTED},g=HttpGenerator{s=START},p=HttpParser{s=START,0 of -1}}{io=0,kio=0,kro=1} idle timeout expired
21:05:08.984 [Scheduler-1874154700] DEBUG org.eclipse.jetty.io.WriteFlusher - failed: WriteFlusher@52b080{IDLE} java.util.concurrent.TimeoutException: Idle timeout expired: 30002/30000 ms
```

-----

It would appear that idle timeout problems are generally fixed in Jetty by setting the `Content-Length` of the response ([which wasn't done in version 0.10.1](https://github.com/dandelion/dandelion/blob/dandelion-0.10.1/dandelion-core/src/main/java/com/github/dandelion/core/web/DandelionFilter.java)).

That said, the problem still occurs when using the current 0.11.0-SNAPSHOT.

I've found a potential workaround as follows:

```diff
diff --git a/dandelion-core/src/main/java/com/github/dandelion/core/web/DandelionFilter.java b/dandelion-core/src/main/java/com/github/dandelion/core/web/DandelionFilter.java
index d2c67f7..61eb49a 100644
--- a/dandelion-core/src/main/java/com/github/dandelion/core/web/DandelionFilter.java
+++ b/dandelion-core/src/main/java/com/github/dandelion/core/web/DandelionFilter.java
@@ -145,7 +145,9 @@ public class DandelionFilter implements Filter {
       }

       response.setContentLength(postHandlerContext.getResponseAsBytes().length);
-      response.getOutputStream().write(postHandlerContext.getResponseAsBytes());
+      if (postHandlerContext.getResponseAsBytes().length > 0) {
+          response.getOutputStream().write(postHandlerContext.getResponseAsBytes());
+      }
    }

    @Override
```

I must admit I haven't tried with other servers or containers. I don't know whether this could be due to an underlying bug in Jetty (for which this would be a workaround), or if this is a Dandelion bug, but with this relatively simple patch, these delays seem to disappear (and so do the exceptions in the logs):

```
21:01:20.782 [qtp191382150-42 - /] DEBUG o.s.web.servlet.DispatcherServlet - Rendering view [org.springframework.web.servlet.view.RedirectView: unnamed; URL [/page1]] in DispatcherServlet with name 'org.springframework.web.servlet.DispatcherServlet-542060780'
21:01:20.782 [qtp191382150-42 - /] DEBUG o.s.b.f.s.DefaultListableBeanFactory - Returning cached instance of singleton bean 'requestDataValueProcessor'
21:01:20.782 [qtp191382150-42 - /] DEBUG o.s.s.w.c.HttpSessionSecurityContextRepository - SecurityContext is empty or contents are anonymous - context will not be stored in HttpSession.
21:01:20.782 [qtp191382150-42 - /] DEBUG o.e.jetty.server.HttpConnection - org.eclipse.jetty.server.HttpConnection$CommitCallback@5cfb60e4 generate: NEED_HEADER (null,[p=0,l=0,c=0,r=0],true)@START
21:01:20.782 [qtp191382150-42 - /] DEBUG o.e.jetty.server.HttpConnection - org.eclipse.jetty.server.HttpConnection$CommitCallback@5cfb60e4 generate: FLUSH ([p=0,l=319,c=8192,r=319],[p=0,l=0,c=0,r=0],true)@COMPLETING
21:01:20.782 [qtp191382150-42 - /] DEBUG org.eclipse.jetty.io.WriteFlusher - write: WriteFlusher@53a1a6a8{IDLE} [HeapByteBuffer@463a4ac8[p=0,l=319,c=8192,r=319]={<<<HTTP/1.1 302 Foun....v20130815)||||>>>deflate, sdch||Ac...???????????????}]
21:01:20.782 [qtp191382150-42 - /] DEBUG org.eclipse.jetty.io.WriteFlusher - update WriteFlusher@53a1a6a8{WRITING}:IDLE-->WRITING
21:01:20.783 [qtp191382150-42 - /] DEBUG org.eclipse.jetty.io.ChannelEndPoint - flushed 319 SelectChannelEndPoint@129cac93{/0:0:0:0:0:0:0:1:60622<r-l>/0:0:0:0:0:0:0:1:9012,o=true,is=false,os=false,fi=FillInterest@16a33a18{false,null},wf=WriteFlusher@53a1a6a8{WRITING},it=30000}{HttpConnection@15b77da5{FILLING},g=HttpGenerator{s=COMPLETING},p=HttpParser{s=END,0 of -1}}{io=0,kio=0,kro=1}
21:01:20.783 [qtp191382150-42 - /] DEBUG org.eclipse.jetty.io.WriteFlusher - flushed true
21:01:20.783 [qtp191382150-42 - /] DEBUG org.eclipse.jetty.io.WriteFlusher - update WriteFlusher@53a1a6a8{IDLE}:WRITING-->IDLE
21:01:20.783 [qtp191382150-42 - /] DEBUG o.e.jetty.server.HttpConnection - org.eclipse.jetty.server.HttpConnection$CommitCallback@5cfb60e4 generate: DONE ([p=319,l=319,c=8192,r=0],[p=0,l=0,c=0,r=0],true)@END
21:01:20.784 [qtp191382150-42 - /] DEBUG o.s.web.servlet.DispatcherServlet - Successfully completed request
21:01:20.784 [qtp191382150-42 - /] DEBUG o.s.s.w.a.ExceptionTranslationFilter - Chain processed normally
21:01:20.784 [qtp191382150-42 - /] DEBUG o.s.s.w.c.SecurityContextPersistenceFilter - SecurityContextHolder now cleared, as request processing completed
21:01:20.784 [qtp191382150-42 - /] DEBUG org.eclipse.jetty.server.Server - RESPONSE /  302 handled=true
21:01:20.784 [qtp191382150-42] DEBUG org.eclipse.jetty.http.HttpParser - reset HttpParser{s=END,0 of -1}
21:01:20.784 [qtp191382150-42] DEBUG org.eclipse.jetty.http.HttpParser - END --> START
21:01:20.784 [qtp191382150-42] DEBUG org.eclipse.jetty.server.HttpChannel - HttpChannelOverHttp@7c446f37{r=5,a=IDLE,uri=-} handle exit, result COMPLETE
```

**Comment by tduchateau** [comment]
Before commenting, could you please recreate the same issue under the [dandelion](https://github.com/dandelion/dandelion/issues) issue tracker? Thanks!

**Comment by harbulot** [comment]
Of course, sorry I should have created there in the first place: https://github.com/dandelion/dandelion/issues/55
