### ISSUE TITLE
NullPointerException after migrating to v1.0.1

### ISSUE THREAD

**Issue by rafaelmembrives** [dandelion/dandelion-datatables#290]
I get a `NullPointerException` after migrating from v0.10.1 to v1.0.1:

    java.lang.NullPointerException
        at com.github.dandelion.core.storage.BundleStorage.storeBundles(BundleStorage.java:105)
        at com.github.dandelion.core.Context.initBundleStorage(Context.java:315)
        at com.github.dandelion.core.Context.init(Context.java:122)
        at com.github.dandelion.core.Context.<init>(Context.java:101)
        at com.github.dandelion.core.web.DandelionFilter.init(DandelionFilter.java:106)

This is my `dandelion.properties` I have excluded the bundles because I wan to manage them myself:

    bundle.excludes = bootstrap3,datatables
    asset.css.excludes = bootstrap3-theme-css
    asset.js.excludes = bootstrap3-theme-js

Thanks in advance.

**Comment by tduchateau** [comment]
Sorry for the delay. Do you remember if your `src/main/resources/dandelion` folder was empty or not?

**Comment by rafaelmembrives** [comment]
Sorry for the delay too. Inside that folder I have these files:

`dandelion.properties`
`datatables/datatables.properties`

**Comment by rafaelmembrives** [comment]
I can´t reproduce the error after some changes. Perhaps a wrong deploy.

Thank you so much.

**Comment by tduchateau** [comment]
Good news :-)
