### ISSUE TITLE
java.math.BigDecimal cannot be cast to java.util.List 

### ISSUE THREAD

**Issue by davduke** [dandelion/dandelion-datatables#301]
Hi I'm using Struts 2 + Spring 3 and I get a java.math.BigDecimal cannot be cast to java.util.List after migrating from v0.9.2 to v1.1.0:

I saw also some colleges on the forum having the same problem:
http://dandelion-forum.48353.x6.nabble.com/java-lang-ClassCastException-td1995.html

I'm trying to make a running a code that is completely working on the previous version:

``` xml
<datatables:table id="vehicles" url="VehicleList.action"  row="vehicle" serverSide="true" processing="true">
   <datatables:column titleKey="web.vehicleList.tableHeader.license" property="license" filterable="true" sortInitDirection="desc"/>
 </datatables:table>
```

The problem is that I blocked, I don't know what could fail :S

LOG:

```
Servlet.service() for servlet jsp threw exception
java.lang.ClassCastException: java.math.BigDecimal cannot be cast to java.util.List
        at com.github.dandelion.datatables.jsp.tag.TableTag.doEndTag(TableTag.java:248)
        at org.apache.jsp.jsp.list.vehicleList_jsp._jspx_meth_datatables_005ftable_005f0(vehicleList_jsp.java:735)
        at org.apache.jsp.jsp.list.vehicleList_jsp._jspx_meth_s_005fform_005f0(vehicleList_jsp.java:544)
        at org.apache.jsp.jsp.list.vehicleList_jsp._jspService(vehicleList_jsp.java:220)
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:432)
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:748)
        at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:604)
        at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:543)
        at org.apache.jasper.runtime.JspRuntimeLibrary.include(JspRuntimeLibrary.java:954)
        at org.apache.jasper.runtime.PageContextImpl.doInclude(PageContextImpl.java:688)
        at org.apache.jasper.runtime.PageContextImpl.include(PageContextImpl.java:682)
        at org.apache.tiles.jsp.context.JspTilesRequestContext.include(JspTilesRequestContext.java:80)
        at org.apache.tiles.jsp.context.JspTilesRequestContext.dispatch(JspTilesRequestContext.java:73)
        at org.apache.tiles.context.TilesRequestContextWrapper.dispatch(TilesRequestContextWrapper.java:72)
```

**Comment by elmehdibahhar** [comment]
Hi,
Did you resolve this issue ?
Thank you

**Comment by mhuzqu** [comment]
Hii All,

my solution is:
- download the TableTag class located in com.github.dandelion.datatables.jsp.tag package.
- put the TableTag  class in your local project (you should put in the same package "com.github.dandelion.datatables.jsp.tag package" and you should create new the package), then comment in line 248, 249 and 250.

re compile and run your project then open the page. the table should rendered perfectly.

:cheers
