### ISSUE TITLE
NullPointerException in DatatablesServlet (Opera)

### ISSUE THREAD

**Issue by tduchateau** [dandelion/dandelion-datatables#39]
_Issue by **[tduchateau](https://github.com/tduchateau)** from Friday Feb 15, 2013 at 13:34 GMT_

----

@karelp
The Opera browser sometimes tends to request the datatables-<random number>.js file multiple times. Multiple requests for the same file cause a NullPointerException because the servlet context attribute is removed after the first request is served and thus `getServletContext().getAttribute(resourceName)` returns null.

Another (related) NPE can be thrown when a request for a resource with an unknown extension is sent to the datatables controller - none of the two conditions in `DatatablesServlet.doGet` is met, `fileContent` remains set to null causing an exception on the later lines.

Stacktrace:
````
Servlet.service() for servlet datatables threw exception: java.lang.NullPointerException
at com.github.datatables4j.core.base.web.servlet.DatatablesServlet.doGet(DatatablesServlet.java:80) [datatables4j-core-base-0.8.2.jar:]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:734) [jboss-servlet-api_3.0_spec-1.0.0.Final.jar:1.0.0.Final]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:847) [jboss-servlet-api_3.0_spec-1.0.0.Final.jar:1.0.0.Final]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:329) [jbossweb-7.0.13.Final.jar:]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248) [jbossweb-7.0.13.Final.jar:]
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:275) [jbossweb-7.0.13.Final.jar:]
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:161) [jbossweb-7.0.13.Final.jar:]
at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:153) [jboss-as-web-7.1.1.Final.jar:7.1.1.Final]
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:155) [jbossweb-7.0.13.Final.jar:]
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102) [jbossweb-7.0.13.Final.jar:]
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109) [jbossweb-7.0.13.Final.jar:]
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:368) [jbossweb-7.0.13.Final.jar:]
at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:877) [jbossweb-7.0.13.Final.jar:]
at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:671) [jbossweb-7.0.13.Final.jar:]
at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:930) [jbossweb-7.0.13.Final.jar:]
at java.lang.Thread.run(Thread.java:662) [rt.jar:1.6.0_37]
````

@tduchateau
Thanks !

It's quite odd, I'll investigate using Opera.

Regarding unknown extensions, it is right but theorically, DataTables4j will only generated HTML tags containing *.js and *.css extensions. Are you trying to use the servlet "manually" ?

@karelp
I think it's more a bug in Opera than in Datatables4j but an unhandled NPE shouldn't occur in a well behaving web application regardless of the user/network input.

Yes, the problem with extensions happens when accessing the servlet directly. Not a big issue but there is always someone trying power browsing and cluttering the logs with NPEs :)

@tduchateau
Reproduced :-/
Anyway, you're right Karelp, I'll try to handle this in a next release. :-)

Thanks !

@karelp
You are awesome :) Thanks.

**Comment by tduchateau** [comment]
Some sample apps have been tested on Opera without any issue.
